import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'
import type { AgentRunStatus, AIProviderName, Confidence, FileCategory, RiskLevel, SandboxStatus, VerificationStatus } from '@/lib/agent/types'

const STATUS_STYLES: Record<AgentRunStatus, string> = {
  planned: 'text-primary border-primary',
  awaiting_diff: 'text-warning border-warning',
  diff_generated: 'text-primary border-primary',
  verification_pending: 'text-warning border-warning',
  verification_failed: 'text-destructive border-destructive',
  verification_passed: 'text-success border-success',
  approved: 'text-success border-success',
  rejected: 'text-destructive border-destructive',
  pr_created: 'text-success border-success',
  failed: 'text-destructive border-destructive',
}

export function StatusBadge({ status }: { status: AgentRunStatus }) {
  return (
    <Badge variant="outline" className={cn('uppercase', STATUS_STYLES[status])}>
      {status.replace(/_/g, ' ')}
    </Badge>
  )
}

const RISK_STYLES: Record<RiskLevel, string> = {
  low: 'text-success border-success',
  medium: 'text-warning border-warning',
  high: 'text-destructive border-destructive',
}

export function RiskBadge({ risk }: { risk: RiskLevel }) {
  return (
    <Badge variant="outline" className={cn('uppercase', RISK_STYLES[risk])}>
      {risk} risk
    </Badge>
  )
}

const VERIFICATION_META: Record<VerificationStatus, { label: string; className: string }> = {
  passed: { label: 'Verification Passed', className: 'text-success border-success' },
  needs_review: { label: 'Needs Review', className: 'text-warning border-warning' },
  failed: { label: 'Failed Verification', className: 'text-destructive border-destructive' },
}

export function VerificationBadge({ status, score }: { status: VerificationStatus; score?: number }) {
  const meta = VERIFICATION_META[status]
  return (
    <Badge variant="outline" className={cn('uppercase', meta.className)}>
      {meta.label}
      {typeof score === 'number' ? ` · ${score}` : ''}
    </Badge>
  )
}

const SANDBOX_META: Record<SandboxStatus, { label: string; className: string }> = {
  not_run: { label: 'Not Run', className: 'text-muted-foreground border-border' },
  running: { label: 'Running', className: 'text-warning border-warning' },
  passed: { label: 'Sandbox Passed', className: 'text-success border-success' },
  failed: { label: 'Sandbox Failed', className: 'text-destructive border-destructive' },
  disabled: { label: 'Disabled', className: 'text-muted-foreground border-border' },
  unavailable: { label: 'Unavailable', className: 'text-warning border-warning' },
}

export function SandboxBadge({ status }: { status: SandboxStatus }) {
  const meta = SANDBOX_META[status]
  return (
    <Badge variant="outline" className={cn('uppercase', meta.className)}>
      {meta.label}
    </Badge>
  )
}

const CONFIDENCE_STYLES: Record<Confidence, string> = {
  high: 'text-success border-success',
  medium: 'text-warning border-warning',
  low: 'text-muted-foreground border-muted-foreground',
}

export function ConfidenceBadge({ confidence }: { confidence: Confidence }) {
  return (
    <Badge variant="outline" className={cn('uppercase', CONFIDENCE_STYLES[confidence])}>
      {confidence} confidence
    </Badge>
  )
}

export function ProviderBadge({ provider, degraded }: { provider: AIProviderName; degraded?: boolean }) {
  return (
    <Badge
      variant="outline"
      className={cn('uppercase', provider === 'mock' ? 'text-warning border-warning' : 'text-primary border-primary')}
      title={
        provider === 'mock'
          ? 'Deterministic mock provider — set OPENAI_API_KEY, GROQ_API_KEY, or ANTHROPIC_API_KEY for AI-written output'
          : `Generated by ${provider}`
      }
    >
      {provider === 'mock' ? 'mock mode' : provider}
      {degraded ? ' (degraded)' : ''}
    </Badge>
  )
}

export const CATEGORY_LABELS: Record<FileCategory, string> = {
  frontend_page: 'Page',
  frontend_component: 'Component',
  backend_api: 'API',
  service_or_lib: 'Service/Lib',
  test: 'Test',
  config: 'Config',
  documentation: 'Docs',
  ci_cd: 'CI/CD',
  database_model: 'DB/Model',
  unknown: 'Other',
}

export function CategoryBadge({ category }: { category: FileCategory }) {
  return (
    <Badge variant="outline" className="text-muted-foreground border-border">
      {CATEGORY_LABELS[category]}
    </Badge>
  )
}
